name: pulsar_cli
description: Command Line Interface for the Pulsar Web Framework.
version: 0.2.5
repository: https://github.com/IgnacioFernandez1311/pulsar_cli
homepage: https://pulsar-web.netlify.app

topics:
  - cli
  - web
  - frontend

executables:
  pulsar: pulsar

environment:
  sdk: ^3.9.2

include:
  - bin/**
  - lib/**
  - lib/src/templates/**
  - pubspec.yaml
  - CHANGELOG.md
  - README.md

dependencies:
  universal_web: ^1.1.1+1
  args: ^2.7.0
  path: ^1.9.1
  pulsar_web: ^0.4.5

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
