name: pulsar_cli
description: Command Line Interface for the Pulsar Web Framework.
version: 0.0.13
repository: https://github.com/IgnacioFernandez1311/pulsar_cli
homepage: https://pulsar-web.netlify.app

topics:
  - cli
  - web
  - frontend

executables:
  pulsar: pulsar

environment:
  sdk: ^3.9.2

include:
  - bin/**
  - lib/**
  - lib/src/templates/**
  - pubspec.yaml
  - CHANGELOG.md
  - README.md

dependencies:
  args: ^2.7.0
  path: ^1.9.1
  pulsar_web: ^0.3.0
  webdev: ^3.0.8

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
